"""knowledge baseline — the schema as it stood at Alembic adoption.

Revision 0001, the base of this service's history.

Generated by ``uv run python scripts/migrate.py baseline knowledge``. Every operation goes
through ``epicurus_core.db.ops`` (``ep.``), which creates a table that is absent and additively
reconciles one that is already there — so this revision applies both to an empty database and
to a deployment provisioned before knowledge adopted Alembic (ADR-XXXX). Later revisions
are ordinary Alembic; only a baseline needs this.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from epicurus_core.db import ops as ep

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create (or additively reconcile) every table knowledge owns."""
    # ### commands auto generated by Alembic - please adjust! ###
    ep.create_table(
        "knowledge_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("note_path", sa.String(length=4096), nullable=False),
        sa.Column("mtime_ns", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "indexed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "note_path", name="uq_knowledge_tenant_note"),
    )
    ep.create_index(ep.f("ix_knowledge_notes_tenant"), "knowledge_notes", ["tenant"], unique=False)
    ep.create_table(
        "knowledge_doc_index",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("note_path", sa.String(length=4096), nullable=False),
        sa.Column("mtime_ns", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "indexed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "note_path", name="uq_knowledge_doc_tenant_note"),
    )
    ep.create_index(
        ep.f("ix_knowledge_doc_index_tenant"), "knowledge_doc_index", ["tenant"], unique=False
    )
    ep.create_table(
        "knowledge_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("note_path", sa.String(length=4096), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_knowledge_versions_tenant"), "knowledge_versions", ["tenant"], unique=False
    )
    ep.create_index(
        "ix_knowledge_versions_tenant_path",
        "knowledge_versions",
        ["tenant", "note_path"],
        unique=False,
    )
    ep.create_table(
        "knowledge_module_docs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("module_name", sa.String(length=63), nullable=False),
        sa.Column("doc_path", sa.String(length=4096), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "indexed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "module_name", "doc_path", name="uq_module_doc"),
    )
    ep.create_index(
        ep.f("ix_knowledge_module_docs_tenant"), "knowledge_module_docs", ["tenant"], unique=False
    )
    ep.create_table(
        "knowledge_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("sid", sa.String(length=32), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("proposed_content", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "origin", sa.String(length=64), server_default=sa.text("'agent'"), nullable=False
        ),
        sa.Column("note", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("to_path", sa.String(length=4096), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_knowledge_suggestions_sid"), "knowledge_suggestions", ["sid"], unique=False
    )
    ep.create_index(
        ep.f("ix_knowledge_suggestions_tenant"), "knowledge_suggestions", ["tenant"], unique=False
    )
    ep.create_table(
        "knowledge_suggestion_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("sid", sa.String(length=32), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column(
            "origin", sa.String(length=64), server_default=sa.text("'agent'"), nullable=False
        ),
        sa.Column("note", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("proposed_content", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("applied_content", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("to_path", sa.String(length=4096), server_default=sa.text("''"), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("proposed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "decided_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_knowledge_suggestion_decisions_tenant"),
        "knowledge_suggestion_decisions",
        ["tenant"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop every table knowledge owns. Destroys data; never automatic."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_knowledge_suggestion_decisions_tenant"),
        table_name="knowledge_suggestion_decisions",
    )
    op.drop_table("knowledge_suggestion_decisions")
    op.drop_index(op.f("ix_knowledge_suggestions_tenant"), table_name="knowledge_suggestions")
    op.drop_index(op.f("ix_knowledge_suggestions_sid"), table_name="knowledge_suggestions")
    op.drop_table("knowledge_suggestions")
    op.drop_index(op.f("ix_knowledge_module_docs_tenant"), table_name="knowledge_module_docs")
    op.drop_table("knowledge_module_docs")
    op.drop_index("ix_knowledge_versions_tenant_path", table_name="knowledge_versions")
    op.drop_index(op.f("ix_knowledge_versions_tenant"), table_name="knowledge_versions")
    op.drop_table("knowledge_versions")
    op.drop_index(op.f("ix_knowledge_doc_index_tenant"), table_name="knowledge_doc_index")
    op.drop_table("knowledge_doc_index")
    op.drop_index(op.f("ix_knowledge_notes_tenant"), table_name="knowledge_notes")
    op.drop_table("knowledge_notes")
    # ### end Alembic commands ###
