"""calendar baseline — the schema as it stood at Alembic adoption.

Revision 0001, the base of this service's history.

Generated by ``uv run python scripts/migrate.py baseline calendar``. Every operation goes
through ``epicurus_core.db.ops`` (``ep.``), which creates a table that is absent and additively
reconciles one that is already there — so this revision applies both to an empty database and
to a deployment provisioned before calendar adopted Alembic (ADR-XXXX). Later revisions
are ordinary Alembic; only a baseline needs this.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from epicurus_core.db import ops as ep

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create (or additively reconcile) every table calendar owns."""
    # ### commands auto generated by Alembic - please adjust! ###
    ep.create_table(
        "calendar_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("start_dt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_dt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=512), nullable=True),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("recurrence", sa.Text(), nullable=True),
        sa.Column("recurring_event_id", sa.String(length=64), nullable=True),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.Column("attendees", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "event_id", name="uq_calendar_tenant_event"),
    )
    ep.create_index(
        ep.f("ix_calendar_events_recurring_event_id"),
        "calendar_events",
        ["recurring_event_id"],
        unique=False,
    )
    ep.create_index(ep.f("ix_calendar_events_tenant"), "calendar_events", ["tenant"], unique=False)
    ep.create_table(
        "calendar_lead_time_prefs",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("lead_minutes", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("tenant"),
    )
    ep.create_table(
        "calendar_fired_markers",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("marker", sa.String(length=32), nullable=False),
        sa.Column("fired_at_ns", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant", "event_id", "marker", name="uq_calendar_fired_marker"),
    )
    ep.create_index(
        ep.f("ix_calendar_fired_markers_event_id"),
        "calendar_fired_markers",
        ["event_id"],
        unique=False,
    )
    ep.create_index(
        ep.f("ix_calendar_fired_markers_tenant"), "calendar_fired_markers", ["tenant"], unique=False
    )
    ep.create_table(
        "calendar_self_writes",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("marker_key", sa.String(length=512), nullable=False),
        sa.Column("expires_at_ns", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant", "marker_key", name="uq_calendar_self_write"),
    )
    ep.create_index(
        ep.f("ix_calendar_self_writes_marker_key"),
        "calendar_self_writes",
        ["marker_key"],
        unique=False,
    )
    ep.create_index(
        ep.f("ix_calendar_self_writes_tenant"), "calendar_self_writes", ["tenant"], unique=False
    )
    ep.create_table(
        "calendar_sync_state",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("account", sa.String(length=64), nullable=False),
        sa.Column("collection", sa.String(length=255), nullable=False),
        sa.Column("sync_token", sa.Text(), nullable=True),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant", "account", "collection", name="uq_calendar_sync_state"),
    )
    ep.create_index(
        ep.f("ix_calendar_sync_state_tenant"), "calendar_sync_state", ["tenant"], unique=False
    )
    ep.create_table(
        "calendar_synced_event",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("account", sa.String(length=64), nullable=False),
        sa.Column("collection", sa.String(length=255), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("series_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("start_dt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_dt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("change_hash", sa.String(length=32), nullable=False),
        sa.Column(
            "seen_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "tenant", "account", "collection", "event_id", name="uq_calendar_synced_event"
        ),
    )
    ep.create_index(
        ep.f("ix_calendar_synced_event_event_id"),
        "calendar_synced_event",
        ["event_id"],
        unique=False,
    )
    ep.create_index(
        ep.f("ix_calendar_synced_event_tenant"), "calendar_synced_event", ["tenant"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop every table calendar owns. Destroys data; never automatic."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calendar_synced_event_tenant"), table_name="calendar_synced_event")
    op.drop_index(op.f("ix_calendar_synced_event_event_id"), table_name="calendar_synced_event")
    op.drop_table("calendar_synced_event")
    op.drop_index(op.f("ix_calendar_sync_state_tenant"), table_name="calendar_sync_state")
    op.drop_table("calendar_sync_state")
    op.drop_index(op.f("ix_calendar_self_writes_tenant"), table_name="calendar_self_writes")
    op.drop_index(op.f("ix_calendar_self_writes_marker_key"), table_name="calendar_self_writes")
    op.drop_table("calendar_self_writes")
    op.drop_index(op.f("ix_calendar_fired_markers_tenant"), table_name="calendar_fired_markers")
    op.drop_index(op.f("ix_calendar_fired_markers_event_id"), table_name="calendar_fired_markers")
    op.drop_table("calendar_fired_markers")
    op.drop_table("calendar_lead_time_prefs")
    op.drop_index(op.f("ix_calendar_events_tenant"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_recurring_event_id"), table_name="calendar_events")
    op.drop_table("calendar_events")
    # ### end Alembic commands ###
