"""storage baseline — the schema as it stood at Alembic adoption.

Revision 0001, the base of this service's history.

Generated by ``uv run python scripts/migrate.py baseline storage``. Every operation goes
through ``epicurus_core.db.ops`` (``ep.``), which creates a table that is absent and additively
reconciles one that is already there — so this revision applies both to an empty database and
to a deployment provisioned before storage adopted Alembic (ADR-XXXX). Later revisions
are ordinary Alembic; only a baseline needs this.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from epicurus_core.db import ops as ep

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create (or additively reconcile) every table storage owns."""
    # ### commands auto generated by Alembic - please adjust! ###
    ep.create_table(
        "storage_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("mtime", sa.Float(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("source", sa.String(length=16), server_default=sa.text("'fs'"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "path", name="uq_storage_tenant_path"),
    )
    ep.create_index(ep.f("ix_storage_files_tenant"), "storage_files", ["tenant"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop every table storage owns. Destroys data; never automatic."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storage_files_tenant"), table_name="storage_files")
    op.drop_table("storage_files")
    # ### end Alembic commands ###
