"""core-app baseline — the schema as it stood at Alembic adoption.

Revision 0001, the base of this service's history.

Generated by ``uv run python scripts/migrate.py baseline core-app``. Every operation goes
through ``epicurus_core.db.ops`` (``ep.``), which creates a table that is absent and additively
reconciles one that is already there — so this revision applies both to an empty database and
to a deployment provisioned before core-app adopted Alembic (ADR-XXXX). Later revisions
are ordinary Alembic; only a baseline needs this.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from epicurus_core.db import ops as ep

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create (or additively reconcile) every table core-app owns."""
    # ### commands auto generated by Alembic - please adjust! ###
    ep.create_table(
        "agent_instructions",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("tenant"),
    )
    ep.create_table(
        "agent_instructions_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vid", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_agent_instructions_versions_tenant"),
        "agent_instructions_versions",
        ["tenant"],
        unique=False,
    )
    ep.create_index(
        ep.f("ix_agent_instructions_versions_vid"),
        "agent_instructions_versions",
        ["vid"],
        unique=False,
    )
    ep.create_table(
        "automation_proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sid", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("path", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("spec", sa.Text(), nullable=False),
        sa.Column("origin", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_automation_proposals_sid"), "automation_proposals", ["sid"], unique=False
    )
    ep.create_index(
        ep.f("ix_automation_proposals_tenant"), "automation_proposals", ["tenant"], unique=False
    )
    ep.create_table(
        "automation_review_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sid", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("path", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("origin", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("proposed_content", sa.Text(), nullable=False),
        sa.Column("applied_content", sa.Text(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("proposed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "decided_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_automation_review_decisions_tenant"),
        "automation_review_decisions",
        ["tenant"],
        unique=False,
    )
    ep.create_table(
        "automation_kill_switch",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("halted", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("tenant"),
    )
    ep.create_table(
        "automation_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("automation_id", sa.String(length=32), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_automation_queue_automation_id"),
        "automation_queue",
        ["automation_id"],
        unique=False,
    )
    ep.create_index(
        ep.f("ix_automation_queue_created_at"), "automation_queue", ["created_at"], unique=False
    )
    ep.create_index(
        ep.f("ix_automation_queue_tenant"), "automation_queue", ["tenant"], unique=False
    )
    ep.create_table(
        "automation_runs",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("automation_id", sa.String(length=32), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("trigger_refs", sa.JSON(), nullable=False),
        sa.Column("filter_verdict", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("sinks_fired", sa.JSON(), nullable=False),
        sa.Column("artifacts", sa.JSON(), nullable=True),
        sa.Column("quiet_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
    )
    ep.create_index(
        ep.f("ix_automation_runs_automation_id"), "automation_runs", ["automation_id"], unique=False
    )
    ep.create_index(ep.f("ix_automation_runs_id"), "automation_runs", ["id"], unique=True)
    ep.create_index(
        ep.f("ix_automation_runs_outcome"), "automation_runs", ["outcome"], unique=False
    )
    ep.create_index(
        ep.f("ix_automation_runs_started_at"), "automation_runs", ["started_at"], unique=False
    )
    ep.create_index(ep.f("ix_automation_runs_tenant"), "automation_runs", ["tenant"], unique=False)
    ep.create_table(
        "automation_sessions",
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("automation_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("chat_mode", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    ep.create_index(
        ep.f("ix_automation_sessions_automation_id"),
        "automation_sessions",
        ["automation_id"],
        unique=False,
    )
    ep.create_index(
        ep.f("ix_automation_sessions_tenant"), "automation_sessions", ["tenant"], unique=False
    )
    ep.create_table(
        "automations",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("event_trigger", sa.JSON(), nullable=True),
        sa.Column("schedule_trigger", sa.JSON(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("autonomy", sa.String(length=20), nullable=False),
        sa.Column("sinks", sa.JSON(), nullable=False),
        sa.Column("chat_mode", sa.String(length=16), nullable=False),
        sa.Column("chat_session_id", sa.String(length=128), nullable=True),
        sa.Column("rate_cap_per_hour", sa.Integer(), nullable=False),
        sa.Column("digest_window_minutes", sa.Integer(), nullable=False),
        sa.Column("sink_config", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=255), nullable=True),
        sa.Column(
            "agent_gated_delivery", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    ep.create_index(ep.f("ix_automations_id"), "automations", ["id"], unique=True)
    ep.create_index(ep.f("ix_automations_tenant"), "automations", ["tenant"], unique=False)
    ep.create_table(
        "module_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("dedup_key", sa.String(length=255), nullable=False),
        sa.Column("entity_ref", sa.JSON(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("causation_id", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "module", "dedup_key", name="uq_module_events_dedup"),
    )
    ep.create_index(
        ep.f("ix_module_events_causation_id"), "module_events", ["causation_id"], unique=False
    )
    ep.create_index(ep.f("ix_module_events_module"), "module_events", ["module"], unique=False)
    ep.create_index(
        ep.f("ix_module_events_received_at"), "module_events", ["received_at"], unique=False
    )
    ep.create_index(ep.f("ix_module_events_tenant"), "module_events", ["tenant"], unique=False)
    ep.create_index(ep.f("ix_module_events_type"), "module_events", ["type"], unique=False)
    ep.create_table(
        "event_subscriptions",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("push", sa.Boolean(), nullable=False),
        sa.Column("center", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant", "module", "event_type", name="uq_event_subscriptions_key"),
    )
    ep.create_index(
        ep.f("ix_event_subscriptions_tenant"), "event_subscriptions", ["tenant"], unique=False
    )
    ep.create_table(
        "core_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("mtime", sa.Float(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "path", name="uq_core_files_tenant_path"),
    )
    ep.create_index(ep.f("ix_core_files_tenant"), "core_files", ["tenant"], unique=False)
    ep.create_table(
        "llm_prefs",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("hidden_models", sa.Text(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("global_default", sa.String(length=256), nullable=True),
        sa.Column("embed_default", sa.String(length=256), nullable=True),
        sa.Column("context_window", sa.Integer(), nullable=True),
        sa.Column("kv_cache_type", sa.String(length=8), nullable=True),
        sa.Column("agent_max_steps", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("tenant"),
    )
    ep.create_table(
        "maintenance_runs",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("jobs_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    ep.create_index(
        ep.f("ix_maintenance_runs_finished_at"), "maintenance_runs", ["finished_at"], unique=False
    )
    ep.create_index(
        ep.f("ix_maintenance_runs_tenant"), "maintenance_runs", ["tenant"], unique=False
    )
    ep.create_table(
        "maintenance_schedule_prefs",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cadence", sa.String(length=16), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("tenant"),
    )
    ep.create_table(
        "agent_attachments",
        sa.Column("att_id", sa.String(length=64), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("kind", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("att_id"),
    )
    ep.create_index(
        ep.f("ix_agent_attachments_tenant"), "agent_attachments", ["tenant"], unique=False
    )
    ep.create_table(
        "agent_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("entity_refs", sa.JSON(), nullable=True),
        sa.Column("attachments", sa.JSON(), nullable=True),
        sa.Column("activity", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_agent_messages_session_id"), "agent_messages", ["session_id"], unique=False
    )
    ep.create_index(ep.f("ix_agent_messages_tenant"), "agent_messages", ["tenant"], unique=False)
    ep.create_table(
        "ephemeral_sessions",
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    ep.create_index(
        ep.f("ix_ephemeral_sessions_tenant"), "ephemeral_sessions", ["tenant"], unique=False
    )
    ep.create_table(
        "memory_extraction_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("user_text", sa.Text(), nullable=False),
        sa.Column("assistant_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_memory_extraction_queue_session_id"),
        "memory_extraction_queue",
        ["session_id"],
        unique=False,
    )
    ep.create_index(
        ep.f("ix_memory_extraction_queue_tenant"),
        "memory_extraction_queue",
        ["tenant"],
        unique=False,
    )
    ep.create_table(
        "standing_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_standing_profiles_tenant"), "standing_profiles", ["tenant"], unique=False
    )
    ep.create_table(
        "model_settings",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("model", sa.String(length=256), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=True),
        sa.Column("keep_alive", sa.String(length=16), nullable=True),
        sa.Column("device", sa.String(length=8), nullable=True),
        sa.PrimaryKeyConstraint("tenant", "model"),
    )
    ep.create_table(
        "module_prefs",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("module", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("removed", sa.Boolean(), nullable=False),
        sa.Column("models", sa.Text(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("disabled_tools", sa.Text(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("collections", sa.Text(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column(
            "suggestions_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("tenant", "module"),
    )
    ep.create_table(
        "notifications",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("deep_link", sa.Text(), nullable=True),
        sa.Column("entity_ref_json", sa.Text(), nullable=True),
        sa.Column("automation_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
    )
    ep.create_index(ep.f("ix_notifications_id"), "notifications", ["id"], unique=True)
    ep.create_index(ep.f("ix_notifications_tenant"), "notifications", ["tenant"], unique=False)
    ep.create_table(
        "page_order_prefs",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("order_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("tenant"),
    )
    ep.create_table(
        "agent_pending_approvals",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("pending_call_id", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("refs", sa.JSON(), nullable=False),
        sa.Column("conversation", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_agent_pending_approvals_tenant"),
        "agent_pending_approvals",
        ["tenant"],
        unique=False,
    )
    ep.create_table(
        "agent_pending_drafts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("pending_call_id", sa.String(length=255), nullable=False),
        sa.Column("tool", sa.String(length=128), nullable=False),
        sa.Column("module", sa.String(length=128), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("draft", sa.JSON(), nullable=False),
        sa.Column("conversation", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_agent_pending_drafts_tenant"), "agent_pending_drafts", ["tenant"], unique=False
    )
    ep.create_table(
        "agent_playbook_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sid", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("origin", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("proposed_content", sa.Text(), nullable=False),
        sa.Column("applied_content", sa.Text(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("proposed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "decided_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_agent_playbook_decisions_tenant"),
        "agent_playbook_decisions",
        ["tenant"],
        unique=False,
    )
    ep.create_table(
        "agent_playbook_proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sid", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("proposed_content", sa.Text(), nullable=False),
        sa.Column("origin", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_agent_playbook_proposals_sid"), "agent_playbook_proposals", ["sid"], unique=False
    )
    ep.create_index(
        ep.f("ix_agent_playbook_proposals_tenant"),
        "agent_playbook_proposals",
        ["tenant"],
        unique=False,
    )
    ep.create_table(
        "agent_playbook_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vid", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("playbook_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_agent_playbook_versions_tenant"),
        "agent_playbook_versions",
        ["tenant"],
        unique=False,
    )
    ep.create_index(
        "ix_agent_playbook_versions_tenant_playbook",
        "agent_playbook_versions",
        ["tenant", "playbook_id"],
        unique=False,
    )
    ep.create_index(
        ep.f("ix_agent_playbook_versions_vid"), "agent_playbook_versions", ["vid"], unique=False
    )
    ep.create_table(
        "agent_playbooks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(ep.f("ix_agent_playbooks_tenant"), "agent_playbooks", ["tenant"], unique=False)
    ep.create_index(
        "ix_agent_playbooks_tenant_name", "agent_playbooks", ["tenant", "name"], unique=True
    )
    ep.create_table(
        "portability_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("progress", sa.JSON(), nullable=True),
        sa.Column("manifest", sa.JSON(), nullable=True),
        sa.Column("preview", sa.JSON(), nullable=True),
        sa.Column("report", sa.JSON(), nullable=True),
        sa.Column("archive_path", sa.String(length=1024), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_portability_jobs_status"), "portability_jobs", ["status"], unique=False
    )
    ep.create_index(
        ep.f("ix_portability_jobs_tenant"), "portability_jobs", ["tenant"], unique=False
    )
    ep.create_table(
        "push_prefs",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("categories", sa.Text(), nullable=False),
        sa.Column("automation_overrides", sa.Text(), nullable=False),
        sa.Column("quiet_hours_enabled", sa.Boolean(), nullable=False),
        sa.Column("quiet_hours_start", sa.String(length=5), nullable=False),
        sa.Column("quiet_hours_end", sa.String(length=5), nullable=False),
        sa.PrimaryKeyConstraint("tenant"),
    )
    ep.create_table(
        "push_queue",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("deep_link", sa.Text(), nullable=True),
        sa.Column("entity_ref_json", sa.Text(), nullable=True),
        sa.Column(
            "queued_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    ep.create_index(ep.f("ix_push_queue_tenant"), "push_queue", ["tenant"], unique=False)
    ep.create_table(
        "push_subscriptions",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.Text(), nullable=False),
        sa.Column("auth", sa.Text(), nullable=False),
        sa.Column("device_label", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant", "endpoint", name="uq_push_subscriptions_tenant_endpoint"),
    )
    ep.create_index(ep.f("ix_push_subscriptions_id"), "push_subscriptions", ["id"], unique=True)
    ep.create_index(
        ep.f("ix_push_subscriptions_tenant"), "push_subscriptions", ["tenant"], unique=False
    )
    ep.create_table(
        "agent_reflection_state",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant"),
    )
    ep.create_table(
        "saved_models",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("model", sa.String(length=256), nullable=False),
        sa.Column("added_at", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("vision_override", sa.String(length=8), nullable=True),
        sa.Column("context_length_override", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("tenant", "model"),
    )
    ep.create_table(
        "scheduled_turns",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("cadence", sa.String(length=16), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=True),
        sa.Column("delivery_target", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
    )
    ep.create_index(ep.f("ix_scheduled_turns_id"), "scheduled_turns", ["id"], unique=True)
    ep.create_index(ep.f("ix_scheduled_turns_tenant"), "scheduled_turns", ["tenant"], unique=False)
    ep.create_table(
        "session_models",
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    ep.create_index(ep.f("ix_session_models_tenant"), "session_models", ["tenant"], unique=False)
    ep.create_table(
        "agent_suspended_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("pending_call_id", sa.String(length=255), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("conversation", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_agent_suspended_runs_tenant"), "agent_suspended_runs", ["tenant"], unique=False
    )
    ep.create_table(
        "timezone_prefs",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("tenant"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop every table core-app owns. Destroys data; never automatic."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timezone_prefs")
    op.drop_index(op.f("ix_agent_suspended_runs_tenant"), table_name="agent_suspended_runs")
    op.drop_table("agent_suspended_runs")
    op.drop_index(op.f("ix_session_models_tenant"), table_name="session_models")
    op.drop_table("session_models")
    op.drop_index(op.f("ix_scheduled_turns_tenant"), table_name="scheduled_turns")
    op.drop_index(op.f("ix_scheduled_turns_id"), table_name="scheduled_turns")
    op.drop_table("scheduled_turns")
    op.drop_table("saved_models")
    op.drop_table("agent_reflection_state")
    op.drop_index(op.f("ix_push_subscriptions_tenant"), table_name="push_subscriptions")
    op.drop_index(op.f("ix_push_subscriptions_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.drop_index(op.f("ix_push_queue_tenant"), table_name="push_queue")
    op.drop_table("push_queue")
    op.drop_table("push_prefs")
    op.drop_index(op.f("ix_portability_jobs_tenant"), table_name="portability_jobs")
    op.drop_index(op.f("ix_portability_jobs_status"), table_name="portability_jobs")
    op.drop_table("portability_jobs")
    op.drop_index("ix_agent_playbooks_tenant_name", table_name="agent_playbooks")
    op.drop_index(op.f("ix_agent_playbooks_tenant"), table_name="agent_playbooks")
    op.drop_table("agent_playbooks")
    op.drop_index(op.f("ix_agent_playbook_versions_vid"), table_name="agent_playbook_versions")
    op.drop_index(
        "ix_agent_playbook_versions_tenant_playbook", table_name="agent_playbook_versions"
    )
    op.drop_index(op.f("ix_agent_playbook_versions_tenant"), table_name="agent_playbook_versions")
    op.drop_table("agent_playbook_versions")
    op.drop_index(op.f("ix_agent_playbook_proposals_tenant"), table_name="agent_playbook_proposals")
    op.drop_index(op.f("ix_agent_playbook_proposals_sid"), table_name="agent_playbook_proposals")
    op.drop_table("agent_playbook_proposals")
    op.drop_index(op.f("ix_agent_playbook_decisions_tenant"), table_name="agent_playbook_decisions")
    op.drop_table("agent_playbook_decisions")
    op.drop_index(op.f("ix_agent_pending_drafts_tenant"), table_name="agent_pending_drafts")
    op.drop_table("agent_pending_drafts")
    op.drop_index(op.f("ix_agent_pending_approvals_tenant"), table_name="agent_pending_approvals")
    op.drop_table("agent_pending_approvals")
    op.drop_table("page_order_prefs")
    op.drop_index(op.f("ix_notifications_tenant"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("module_prefs")
    op.drop_table("model_settings")
    op.drop_index(op.f("ix_standing_profiles_tenant"), table_name="standing_profiles")
    op.drop_table("standing_profiles")
    op.drop_index(op.f("ix_memory_extraction_queue_tenant"), table_name="memory_extraction_queue")
    op.drop_index(
        op.f("ix_memory_extraction_queue_session_id"), table_name="memory_extraction_queue"
    )
    op.drop_table("memory_extraction_queue")
    op.drop_index(op.f("ix_ephemeral_sessions_tenant"), table_name="ephemeral_sessions")
    op.drop_table("ephemeral_sessions")
    op.drop_index(op.f("ix_agent_messages_tenant"), table_name="agent_messages")
    op.drop_index(op.f("ix_agent_messages_session_id"), table_name="agent_messages")
    op.drop_table("agent_messages")
    op.drop_index(op.f("ix_agent_attachments_tenant"), table_name="agent_attachments")
    op.drop_table("agent_attachments")
    op.drop_table("maintenance_schedule_prefs")
    op.drop_index(op.f("ix_maintenance_runs_tenant"), table_name="maintenance_runs")
    op.drop_index(op.f("ix_maintenance_runs_finished_at"), table_name="maintenance_runs")
    op.drop_table("maintenance_runs")
    op.drop_table("llm_prefs")
    op.drop_index(op.f("ix_core_files_tenant"), table_name="core_files")
    op.drop_table("core_files")
    op.drop_index(op.f("ix_event_subscriptions_tenant"), table_name="event_subscriptions")
    op.drop_table("event_subscriptions")
    op.drop_index(op.f("ix_module_events_type"), table_name="module_events")
    op.drop_index(op.f("ix_module_events_tenant"), table_name="module_events")
    op.drop_index(op.f("ix_module_events_received_at"), table_name="module_events")
    op.drop_index(op.f("ix_module_events_module"), table_name="module_events")
    op.drop_index(op.f("ix_module_events_causation_id"), table_name="module_events")
    op.drop_table("module_events")
    op.drop_index(op.f("ix_automations_tenant"), table_name="automations")
    op.drop_index(op.f("ix_automations_id"), table_name="automations")
    op.drop_table("automations")
    op.drop_index(op.f("ix_automation_sessions_tenant"), table_name="automation_sessions")
    op.drop_index(op.f("ix_automation_sessions_automation_id"), table_name="automation_sessions")
    op.drop_table("automation_sessions")
    op.drop_index(op.f("ix_automation_runs_tenant"), table_name="automation_runs")
    op.drop_index(op.f("ix_automation_runs_started_at"), table_name="automation_runs")
    op.drop_index(op.f("ix_automation_runs_outcome"), table_name="automation_runs")
    op.drop_index(op.f("ix_automation_runs_id"), table_name="automation_runs")
    op.drop_index(op.f("ix_automation_runs_automation_id"), table_name="automation_runs")
    op.drop_table("automation_runs")
    op.drop_index(op.f("ix_automation_queue_tenant"), table_name="automation_queue")
    op.drop_index(op.f("ix_automation_queue_created_at"), table_name="automation_queue")
    op.drop_index(op.f("ix_automation_queue_automation_id"), table_name="automation_queue")
    op.drop_table("automation_queue")
    op.drop_table("automation_kill_switch")
    op.drop_index(
        op.f("ix_automation_review_decisions_tenant"), table_name="automation_review_decisions"
    )
    op.drop_table("automation_review_decisions")
    op.drop_index(op.f("ix_automation_proposals_tenant"), table_name="automation_proposals")
    op.drop_index(op.f("ix_automation_proposals_sid"), table_name="automation_proposals")
    op.drop_table("automation_proposals")
    op.drop_index(
        op.f("ix_agent_instructions_versions_vid"), table_name="agent_instructions_versions"
    )
    op.drop_index(
        op.f("ix_agent_instructions_versions_tenant"), table_name="agent_instructions_versions"
    )
    op.drop_table("agent_instructions_versions")
    op.drop_table("agent_instructions")
    # ### end Alembic commands ###
