"""tasks baseline — the schema as it stood at Alembic adoption.

Revision 0001, the base of this service's history.

Generated by ``uv run python scripts/migrate.py baseline tasks``. Every operation goes
through ``epicurus_core.db.ops`` (``ep.``), which creates a table that is absent and additively
reconciles one that is already there — so this revision applies both to an empty database and
to a deployment provisioned before tasks adopted Alembic (ADR-XXXX). Later revisions
are ordinary Alembic; only a baseline needs this.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from epicurus_core.db import ops as ep

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create (or additively reconcile) every table tasks owns."""
    # ### commands auto generated by Alembic - please adjust! ###
    ep.create_table(
        "task_repeats",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("list_id", sa.String(length=255), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("rrule", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant_id", "list_id", "task_id", name="uq_task_repeats"),
    )
    ep.create_index(ep.f("ix_task_repeats_task_id"), "task_repeats", ["task_id"], unique=False)
    ep.create_index(ep.f("ix_task_repeats_tenant_id"), "task_repeats", ["tenant_id"], unique=False)
    ep.create_table(
        "tasks_local",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("due", sa.String(length=64), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("repeat", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_tasks_tenant_id"),
    )
    ep.create_index(ep.f("ix_tasks_local_id"), "tasks_local", ["id"], unique=False)
    ep.create_index(ep.f("ix_tasks_local_tenant_id"), "tasks_local", ["tenant_id"], unique=False)
    ep.create_table(
        "tasks_lead_time_prefs",
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("lead_days", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("tenant"),
    )
    ep.create_table(
        "tasks_fired_markers",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("marker", sa.String(length=32), nullable=False),
        sa.Column("fired_at_ns", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant", "task_id", "marker", name="uq_tasks_fired_marker"),
    )
    ep.create_index(
        ep.f("ix_tasks_fired_markers_task_id"), "tasks_fired_markers", ["task_id"], unique=False
    )
    ep.create_index(
        ep.f("ix_tasks_fired_markers_tenant"), "tasks_fired_markers", ["tenant"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop every table tasks owns. Destroys data; never automatic."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_fired_markers_tenant"), table_name="tasks_fired_markers")
    op.drop_index(op.f("ix_tasks_fired_markers_task_id"), table_name="tasks_fired_markers")
    op.drop_table("tasks_fired_markers")
    op.drop_table("tasks_lead_time_prefs")
    op.drop_index(op.f("ix_tasks_local_tenant_id"), table_name="tasks_local")
    op.drop_index(op.f("ix_tasks_local_id"), table_name="tasks_local")
    op.drop_table("tasks_local")
    op.drop_index(op.f("ix_task_repeats_tenant_id"), table_name="task_repeats")
    op.drop_index(op.f("ix_task_repeats_task_id"), table_name="task_repeats")
    op.drop_table("task_repeats")
    # ### end Alembic commands ###
