"""epicurus-core — shared contract and runtime for epicurus services.

Cross-service building blocks: configuration, structured logging, the tenant
scoping primitive, the NATS event backbone, the MCP module contract, the OpenBao
secret client, and the operational ``/health`` + ``/metrics`` surface.
"""

from __future__ import annotations

from epicurus_core._version import __version__
from epicurus_core.config import CoreSettings, Environment, LogLevel
from epicurus_core.contracts import (
    LIST_CAP,
    LOCAL_ACCOUNT,
    Account,
    AccountsView,
    Attachment,
    AttachmentSource,
    ChatMessage,
    ChatResult,
    Collection,
    CollectionPrefs,
    CollectionRef,
    DraftReview,
    EntityRef,
    HoverCard,
    HoverCardDetail,
    HoverCardLink,
    PlatformChatResponse,
    PlatformMessage,
    Role,
    ToolEnvelope,
    capped_listing,
    draft_review,
    tool_envelope,
)
from epicurus_core.events import Event, EventBus, EventHandler, Payload, Replier
from epicurus_core.files import (
    FileEntry,
    FileKind,
    FileStore,
    LocalFileStore,
    S3FileStore,
    build_file_store,
)
from epicurus_core.logging import configure_logging, get_logger
from epicurus_core.manifest import (
    CONTRACT_VERSION,
    CollectionsSpec,
    EventSpec,
    ModelRole,
    ModelSlot,
    ModuleManifest,
    PageArchetype,
    PageSpec,
    ToolSpec,
    UiAction,
    UiSection,
)
from epicurus_core.messaging import (
    MESSAGING_INBOUND,
    MESSAGING_OUTBOUND,
    InboundMessage,
    MessageAttachment,
    OutboundMessage,
    session_id_for,
)
from epicurus_core.module import EpicurusModule, add_manifest_route
from epicurus_core.observability import HealthResponse, add_ops_routes, create_ops_router
from epicurus_core.platform_client import PlatformClient
from epicurus_core.review import (
    ApplyResult,
    ApproveBody,
    ReviewAuditData,
    ReviewData,
    ReviewDecision,
    ReviewSuggestion,
)
from epicurus_core.routing import route_paths
from epicurus_core.secret_store import SecretError, SecretStore
from epicurus_core.tenancy import (
    TenantError,
    current_tenant,
    is_valid_tenant_id,
    reset_current_tenant,
    scope_bucket,
    scope_collection,
    scope_secret_path,
    scope_subject,
    set_current_tenant,
    validate_tenant_id,
)
from epicurus_core.tracing import get_tracer, setup_tracing

__all__ = [
    "CONTRACT_VERSION",
    "LIST_CAP",
    "LOCAL_ACCOUNT",
    "MESSAGING_INBOUND",
    "MESSAGING_OUTBOUND",
    "Account",
    "AccountsView",
    "ApplyResult",
    "ApproveBody",
    "Attachment",
    "AttachmentSource",
    "ChatMessage",
    "ChatResult",
    "Collection",
    "CollectionPrefs",
    "CollectionRef",
    "CollectionsSpec",
    "CoreSettings",
    "DraftReview",
    "EntityRef",
    "Environment",
    "EpicurusModule",
    "Event",
    "EventBus",
    "EventHandler",
    "EventSpec",
    "FileEntry",
    "FileKind",
    "FileStore",
    "HealthResponse",
    "HoverCard",
    "HoverCardDetail",
    "HoverCardLink",
    "InboundMessage",
    "LocalFileStore",
    "LogLevel",
    "MessageAttachment",
    "ModelRole",
    "ModelSlot",
    "ModuleManifest",
    "OutboundMessage",
    "PageArchetype",
    "PageSpec",
    "Payload",
    "PlatformChatResponse",
    "PlatformClient",
    "PlatformMessage",
    "Replier",
    "ReviewAuditData",
    "ReviewData",
    "ReviewDecision",
    "ReviewSuggestion",
    "Role",
    "S3FileStore",
    "SecretError",
    "SecretStore",
    "TenantError",
    "ToolEnvelope",
    "ToolSpec",
    "UiAction",
    "UiSection",
    "__version__",
    "add_manifest_route",
    "add_ops_routes",
    "build_file_store",
    "capped_listing",
    "configure_logging",
    "create_ops_router",
    "current_tenant",
    "draft_review",
    "get_logger",
    "get_tracer",
    "is_valid_tenant_id",
    "reset_current_tenant",
    "route_paths",
    "scope_bucket",
    "scope_collection",
    "scope_secret_path",
    "scope_subject",
    "session_id_for",
    "set_current_tenant",
    "setup_tracing",
    "tool_envelope",
    "validate_tenant_id",
]
