#!/usr/bin/env python3
"""Every schema-migration chore, in one place: baseline, new, check, gate, services.

Schema is Alembic-managed, one migration environment per service (#834, ADR-XXXX). This
script is the only entry point for authoring and verifying those environments — the Taskfile
(`task migrate:new`, `task migrate:check`) and the `migrations` CI job both call it, so the
gate and the developer run the same code.

    uv run python scripts/migrate.py services
        List the services whose schema is migration-managed, and each one's head revision.

    uv run python scripts/migrate.py baseline <service>
        Render `versions/0001_baseline.py` from the service's models. Writes once; refuses to
        overwrite. See `_render_baseline` for why this is safe to do without Postgres.

    uv run python scripts/migrate.py new <service> "<message>"
        Create the next empty revision for hand-writing. *Not* autogenerate — that needs a
        live Postgres holding the previous schema, which the docker-light local setup does not
        have, and a revision guessed against SQLite would render Postgres-wrong DDL. Write the
        `op.*` calls yourself and let `check` below prove they match the models.

    uv run python scripts/migrate.py check [<service> ...] [--url URL]
        Upgrade an empty database to head, then `alembic check`: fail if the models and the
        revisions disagree — i.e. if a model changed and nobody wrote a revision. Defaults to
        a throwaway SQLite file, so it is a second-long local gate; pass `--url` to run it
        against Postgres.

    uv run python scripts/migrate.py gate --url URL
        What CI runs, against real Postgres, for every migration-managed service: the fresh
        install, the drift check, and the pre-Alembic adoption path — each on a database of
        its own. See `_gate_service`.

Services are discovered by glob (`services/*/src/*/migrations/env.py`), never from a list in
this file or in the workflow: a service lane adopts migrations by adding that directory, and
is covered by the gate from that commit on with nothing else to remember.
"""

from __future__ import annotations

import argparse
import asyncio
import importlib
import re
import shutil
import subprocess
import sys
import tempfile
from collections.abc import AsyncIterator, Sequence
from contextlib import asynccontextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal, cast

import sqlalchemy as sa
from alembic import command
from alembic.autogenerate import produce_migrations, render_python_code
from alembic.autogenerate.api import AutogenContext
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from alembic.util import AutogenerateDiffsDetected, CommandError
from sqlalchemy import MetaData
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.schema import ColumnCollectionConstraint, DefaultClause
from sqlalchemy.sql.functions import now as sql_now

from epicurus_core.db import ops
from epicurus_core.db.migrations import alembic_config, run_migrations, version_table_name

REPO_ROOT = Path(__file__).resolve().parent.parent

#: Every migration-managed service has this file; nothing else in the tree does.
_DISCOVERY_GLOB = "services/*/src/*/migrations/env.py"

#: Header of a generated or hand-written revision. `from __future__` and the explicit
#: annotations keep the file inside the repo's strict mypy gate like any other source file.
_REVISION_TEMPLATE = '''"""{message}

Revision {revision}, {parent_clause}.
{body_note}
"""

from __future__ import annotations

from collections.abc import Sequence
{extra_imports}
revision: str = "{revision}"
down_revision: str | None = {down_revision}
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """{upgrade_doc}"""
{upgrade_body}


def downgrade() -> None:
    """{downgrade_doc}"""
{downgrade_body}
'''


class MigrateError(RuntimeError):
    """A chore could not be completed — reported as a one-line error, not a traceback."""


@dataclass(frozen=True)
class Service:
    """One migration-managed service, as discovered on disk and loaded from its package."""

    name: str
    package: str
    script_location: Path
    metadatas: list[MetaData]

    @property
    def version_table(self) -> str:
        return version_table_name(self.name)

    @property
    def versions_dir(self) -> Path:
        return self.script_location / "versions"

    def head(self) -> str | None:
        """The head revision in this service's `versions/`, or ``None`` if there is none yet."""
        config = alembic_config(
            script_location=self.script_location,
            metadatas=self.metadatas,
            version_table=self.version_table,
        )
        return ScriptDirectory.from_config(config).get_current_head()


# ── Discovery ─────────────────────────────────────────────────────────────────


def discover() -> list[Service]:
    """Every migration-managed service, in a stable order."""
    services = [_load(env_py) for env_py in sorted(REPO_ROOT.glob(_DISCOVERY_GLOB))]
    if not services:
        raise MigrateError(f"no migration-managed service found under {_DISCOVERY_GLOB}")
    return services


def select(names: Sequence[str]) -> list[Service]:
    """The named services, or all of them when *names* is empty."""
    services = discover()
    if not names:
        return services
    by_name = {service.name: service for service in services}
    missing = [name for name in names if name not in by_name]
    if missing:
        known = ", ".join(sorted(by_name))
        raise MigrateError(f"not migration-managed: {', '.join(missing)} (known: {known})")
    return [by_name[name] for name in names]


def _load(env_py: Path) -> Service:
    """Load one service's migration environment from its ``<package>.migrations`` module.

    The module exports ``SERVICE``, ``SCRIPT_LOCATION`` and ``METADATAS`` and imports only its
    store modules — never the service's app — so this stays a cheap import that needs no
    settings, no database and no network.
    """
    package = env_py.parent.parent.name
    service_dir = env_py.parents[3].name
    module = importlib.import_module(f"{package}.migrations")
    name = getattr(module, "SERVICE", None)
    script_location = getattr(module, "SCRIPT_LOCATION", None)
    metadatas = getattr(module, "METADATAS", None)
    if name != service_dir:
        raise MigrateError(
            f"{package}.migrations.SERVICE is {name!r} but the service directory is "
            f"{service_dir!r} — they name the same thing and must agree (the version table, "
            f"the advisory lock and the gate all key on it)"
        )
    if not isinstance(script_location, Path) or not metadatas:
        raise MigrateError(
            f"{package}.migrations must export SCRIPT_LOCATION (a Path) and METADATAS "
            f"(a non-empty sequence of MetaData)"
        )
    return Service(
        name=name,
        package=package,
        script_location=script_location,
        metadatas=list(metadatas),
    )


# ── Rendering a revision ──────────────────────────────────────────────────────


def _render_server_default(default: object) -> str | Literal[False]:
    """Render a column's server default faithfully, or refuse.

    Alembic's own renderer is lossy here, and in a way that produces DDL that *fails on
    Postgres*: it strips the surrounding quotes from a literal default (`server_default="'fs'"`
    renders as `server_default='fs'`, which SQLAlchemy then emits as the bare SQL token `fs`),
    and it compiles a function default against whatever dialect is connected — so a baseline
    rendered against SQLite would carry SQLite's `(CURRENT_TIMESTAMP)` into a Postgres
    migration. Both are invisible until the revision runs.

    So the two forms this repo actually uses are rendered explicitly and dialect-neutrally:
    a literal SQL string as `sa.text(<the string, verbatim>)`, and `func.now()` as itself, so
    SQLAlchemy compiles it per dialect at DDL time. Anything else raises rather than guessing —
    a server default that reaches production wrong is exactly the class of defect this whole
    migration framework exists to remove.
    """
    if not isinstance(default, DefaultClause):
        return False
    arg = default.arg
    text = getattr(arg, "text", None)
    if isinstance(arg, str):
        return f"sa.text({arg!r})"
    if isinstance(arg, sql_now):
        return "sa.func.now()"
    if isinstance(text, str):
        return f"sa.text({text!r})"
    raise MigrateError(
        f"cannot render server default {arg!r} dialect-neutrally — add it to "
        f"scripts/migrate.py:_render_server_default, or give the column a literal "
        f"server_default instead"
    )


def _render_item(type_: str, obj: Any, autogen_context: AutogenContext) -> str | Literal[False]:
    """Alembic render hook: take over server defaults, leave everything else to Alembic."""
    if type_ == "server_default":
        return _render_server_default(obj)
    return False


def _render_baseline(service: Service) -> str:
    """Render the baseline revision's body from the service's models, with no database.

    The diff is taken against an **empty in-memory SQLite** database, which sounds like a
    portability hazard and is not: from empty, the only operations autogenerate can produce are
    `create_table` and `create_index`, and those are rendered from the *model metadata* — never
    from reflection — so nothing about the connected dialect reaches the output. (Server
    defaults were the one exception, which `_render_server_default` above now handles.) That is
    what makes a baseline authorable on a laptop with no Postgres.

    The upgrade body is rendered against `epicurus_core.db.ops` (`ep.`) rather than `op.`, so
    the baseline is idempotent and one `upgrade head` serves an empty database and a
    pre-Alembic one alike. The downgrade body is ordinary `op.` — dropping tables needs no
    such care.
    """
    engine = sa.create_engine("sqlite://")
    try:
        with engine.connect() as conn:
            context = MigrationContext.configure(
                connection=conn,
                opts={
                    "target_metadata": service.metadatas,
                    "compare_type": True,
                    "compare_server_default": True,
                    "render_as_batch": True,
                },
            )
            # `produce_migrations` is typed for a single MetaData and documented to accept a
            # sequence (a service has one DeclarativeBase per store module, so a list is the
            # normal case here); the cast is the type stub catching up, not a behaviour change.
            script = produce_migrations(context, cast("MetaData", service.metadatas))
            if script.upgrade_ops is None or script.downgrade_ops is None:
                raise MigrateError(f"{service.name}: autogenerate produced no operations")
            upgrade = render_python_code(
                script.upgrade_ops,
                alembic_module_prefix="ep.",
                # Explicitly NOT batch mode, even though env.py renders autogenerate diffs that
                # way: batch mode wraps a `create_index` in `op.batch_alter_table(...)`, which
                # both bypasses the idempotent `ep.` shim and, on SQLite, can rebuild the whole
                # table. A baseline only ever creates tables and indexes — neither needs it.
                # Later revisions that genuinely alter a column are hand-written and reach for
                # `op.batch_alter_table` themselves.
                render_as_batch=False,
                migration_context=context,
                render_item=_render_item,
            )
            downgrade = render_python_code(
                script.downgrade_ops,
                # Explicitly NOT batch mode, even though env.py renders autogenerate diffs that
                # way: batch mode wraps a `create_index` in `op.batch_alter_table(...)`, which
                # both bypasses the idempotent `ep.` shim and, on SQLite, can rebuild the whole
                # table. A baseline only ever creates tables and indexes — neither needs it.
                # Later revisions that genuinely alter a column are hand-written and reach for
                # `op.batch_alter_table` themselves.
                render_as_batch=False,
                migration_context=context,
                render_item=_render_item,
            )
    finally:
        engine.dispose()
    _reject_unshimmed_ops(service, upgrade)
    return _REVISION_TEMPLATE.format(
        message=f"{service.name} baseline — the schema as it stood at Alembic adoption.",
        revision="0001",
        parent_clause="the base of this service's history",
        body_note=(
            "\nGenerated by ``uv run python scripts/migrate.py baseline "
            f"{service.name}``. Every operation goes\nthrough ``epicurus_core.db.ops``"
            " (``ep.``), which creates a table that is absent and additively\nreconciles one"
            " that is already there — so this revision applies both to an empty database and"
            f"\nto a deployment provisioned before {service.name} adopted Alembic (ADR-XXXX)."
            " Later revisions\nare ordinary Alembic; only a baseline needs this."
        ),
        extra_imports=(
            "\nimport sqlalchemy as sa\nfrom alembic import op\n\n"
            "from epicurus_core.db import ops as ep\n"
        ),
        down_revision="None",
        upgrade_doc=f"Create (or additively reconcile) every table {service.name} owns.",
        upgrade_body=upgrade,
        downgrade_doc=f"Drop every table {service.name} owns. Destroys data; never automatic.",
        downgrade_body=downgrade,
    )


def _reject_unshimmed_ops(service: Service, rendered: str) -> None:
    """Fail if the baseline uses an `ep.` operation `epicurus_core.db.ops` does not provide.

    From an empty database Alembic emits only `create_table` and `create_index`, so this should
    never trip — and if a future SQLAlchemy or Alembic makes it trip, the right outcome is a
    loud failure here rather than a baseline that raises `AttributeError` halfway through a
    production upgrade.
    """
    used = set(re.findall(r"\bep\.([a-zA-Z_][a-zA-Z0-9_]*)\(", rendered))
    unknown = sorted(name for name in used if not hasattr(ops, name))
    if unknown:
        raise MigrateError(
            f"{service.name}'s baseline needs idempotent versions of {', '.join(unknown)}, "
            f"which epicurus_core.db.ops does not provide — add them there first"
        )


def _format(path: Path) -> None:
    """Run ruff over a generated file so it lands already matching the repo's gates."""
    ruff = shutil.which("ruff")
    if ruff is None:
        print(f"  note: ruff not on PATH — run `uv run ruff format {path}` before committing")
        return
    subprocess.run([ruff, "format", "-q", str(path)], check=False, cwd=REPO_ROOT)
    subprocess.run([ruff, "check", "-q", "--fix", str(path)], check=False, cwd=REPO_ROOT)


# ── Commands ──────────────────────────────────────────────────────────────────


def cmd_services(_: argparse.Namespace) -> int:
    """List the migration-managed services, their version table and their head revision."""
    for service in discover():
        head = service.head() or "(no revisions yet)"
        revisions = len(list(service.versions_dir.glob("*.py")))
        print(f"{service.name:<12} head={head:<20} revisions={revisions} {service.version_table}")
    return 0


def cmd_baseline(args: argparse.Namespace) -> int:
    """Write `versions/0001_baseline.py` for a service that has no revisions yet."""
    (service,) = select([args.service])
    existing = sorted(service.versions_dir.glob("*.py"))
    if existing:
        raise MigrateError(
            f"{service.name} already has revisions ({', '.join(p.name for p in existing)}) — a "
            f"baseline is written once; use `new` for a subsequent change"
        )
    service.versions_dir.mkdir(parents=True, exist_ok=True)
    path = service.versions_dir / "0001_baseline.py"
    path.write_text(_render_baseline(service), encoding="utf-8")
    _format(path)
    print(f"wrote {path.relative_to(REPO_ROOT)}")
    print(f"  next: uv run python scripts/migrate.py check {service.name}")
    return 0


def cmd_new(args: argparse.Namespace) -> int:
    """Create the next empty revision for a service, for hand-writing."""
    (service,) = select([args.service])
    head = service.head()
    if head is None:
        raise MigrateError(
            f"{service.name} has no baseline yet — run `baseline {service.name}` first"
        )
    revision = f"{int(head) + 1:04d}" if head.isdigit() else None
    if revision is None:
        raise MigrateError(
            f"{service.name}'s head revision {head!r} is not a zero-padded number; this "
            f"repo's revision ids are 0001, 0002, … — rename it or extend this command"
        )
    slug = "_".join(part for part in args.message.lower().replace("-", " ").split() if part)
    path = service.versions_dir / f"{revision}_{slug}.py"
    if path.exists():
        raise MigrateError(f"{path.relative_to(REPO_ROOT)} already exists")
    body = (
        "    # Hand-written: autogenerate needs a live Postgres holding the previous schema,\n"
        "    # which the docker-light local setup does not have. Write the op.* calls (add\n"
        "    # `from alembic import op` and `import sqlalchemy as sa` above as you need them),\n"
        "    # then prove them against the models with\n"
        f"    #   uv run python scripts/migrate.py check {service.name}\n"
        "    raise NotImplementedError"
    )
    path.write_text(
        _REVISION_TEMPLATE.format(
            message=f"{args.message}",
            revision=revision,
            parent_clause=f"following {head}",
            body_note="",
            extra_imports="",
            down_revision=f'"{head}"',
            upgrade_doc="Apply the change.",
            upgrade_body=body,
            downgrade_doc="Reverse the change.",
            downgrade_body=body,
        ),
        encoding="utf-8",
    )
    _format(path)
    print(f"wrote {path.relative_to(REPO_ROOT)}")
    print(f"  then: uv run python scripts/migrate.py check {service.name}")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    """Upgrade an empty database to head, then fail on any model↔revision drift."""
    services = select(args.services)
    failures: list[str] = []
    for service in services:
        print(f"→ {service.name}: upgrade head from empty, then alembic check")
        try:
            asyncio.run(_check_one(service, args.url))
        except AutogenerateDiffsDetected as exc:
            failures.append(f"{service.name}: {exc}")
            print(f"  DRIFT {exc}")
        except CommandError as exc:
            failures.append(f"{service.name}: {type(exc).__name__}: {exc}")
            print(f"  FAILED {type(exc).__name__}: {exc}")
        else:
            print("  ok")
    if failures:
        print()
        print("models and revisions disagree — write a revision for the change:")
        for failure in failures:
            print(f"  {failure}")
        print('  uv run python scripts/migrate.py new <service> "<what changed>"')
        return 1
    return 0


def cmd_gate(args: argparse.Namespace) -> int:
    """The CI gate: fresh install, drift, and the pre-Alembic adoption path, on real Postgres."""
    failures: list[str] = []
    for service in select(args.services):
        print(f"::group::migrations gate — {service.name}")
        try:
            asyncio.run(_gate_service(service, args.url))
        except (AssertionError, AutogenerateDiffsDetected, CommandError, MigrateError) as exc:
            failures.append(f"{service.name}: {type(exc).__name__}: {exc}")
            print(f"FAILED {type(exc).__name__}: {exc}")
        print("::endgroup::")
    if failures:
        print()
        for failure in failures:
            print(f"::error::migrations gate: {failure}")
        return 1
    print("migrations gate: every service installs fresh, adopts cleanly, and matches its models")
    return 0


# ── The work behind `check` and `gate` ────────────────────────────────────────


async def _check_one(service: Service, url: str | None) -> None:
    """`upgrade head` on an empty database, then `alembic check`."""
    with tempfile.TemporaryDirectory() as tmp:
        target = url or f"sqlite+aiosqlite:///{Path(tmp) / 'check.sqlite'}"
        engine = create_async_engine(target)
        try:
            await run_migrations(
                engine,
                service=service.name,
                script_location=service.script_location,
                metadatas=service.metadatas,
            )
            async with engine.connect() as conn:
                await conn.run_sync(_alembic_check, service)
        finally:
            await engine.dispose()


def _alembic_check(sync_conn: Connection, service: Service) -> None:
    """`alembic check` against the live connection — raises `AutogenerateDiffsDetected`."""
    command.check(
        alembic_config(
            script_location=service.script_location,
            metadatas=service.metadatas,
            version_table=service.version_table,
            connection=sync_conn,
        )
    )


async def _gate_service(service: Service, url: str) -> None:
    """Prove the three things only a real Postgres can prove, each on its own database.

    1. **Fresh install.** An empty database reaches head, is classified `fresh`, and then
       matches the models exactly (`alembic check`) — which is the gate the owner asked for on
       #834: a model changed with no revision fails here, with the diff named.
    2. **Idempotent restart.** Running it again is classified `managed` and changes nothing.
    3. **Adoption of a pre-Alembic database.** The old `create_all` path builds the schema,
       then the migrations run: head is reached, the database is classified `adopted`, and it
       still matches the models. Nothing in the repo exercised an upgrade before this.
    4. **Adoption of a *drifted* pre-Alembic database.** The same, but with the columns the
       additive reconcile was responsible for dropped first — exactly the state #214 and #218
       were reported from. The baseline has to repair them, and `alembic check` has to agree
       afterwards.
    """
    async with _database(url, f"epi_gate_{service.name}_fresh") as fresh:
        outcome = await _upgrade(service, fresh)
        assert outcome == "fresh", f"empty database classified {outcome!r}, expected 'fresh'"
        await _assert_no_drift(service, fresh)
        print("  fresh install → head, no drift")
        outcome = await _upgrade(service, fresh)
        assert outcome == "managed", f"second run classified {outcome!r}, expected 'managed'"
        print("  second run → managed, no-op")

    async with _database(url, f"epi_gate_{service.name}_adopt") as adopt:
        await _build_pre_alembic(service, adopt, drop_reconciled=False)
        outcome = await _upgrade(service, adopt)
        assert outcome == "adopted", f"pre-Alembic database classified {outcome!r}"
        await _assert_no_drift(service, adopt)
        print("  pre-Alembic database → adopted, head, no drift")

    dropped_any = False
    async with _database(url, f"epi_gate_{service.name}_drift") as drift:
        dropped_any = await _build_pre_alembic(service, drift, drop_reconciled=True)
        if dropped_any:
            outcome = await _upgrade(service, drift)
            assert outcome == "adopted", f"drifted database classified {outcome!r}"
            await _assert_no_drift(service, drift)
            print("  drifted pre-Alembic database → repaired by the baseline, no drift")
    if not dropped_any:
        print("  no additively-reconcilable column in this service — drift arm skipped")


async def _upgrade(service: Service, url: str) -> str:
    engine = create_async_engine(url)
    try:
        return await run_migrations(
            engine,
            service=service.name,
            script_location=service.script_location,
            metadatas=service.metadatas,
        )
    finally:
        await engine.dispose()


async def _assert_no_drift(service: Service, url: str) -> None:
    engine = create_async_engine(url)
    try:
        async with engine.connect() as conn:
            await conn.run_sync(_alembic_check, service)
    finally:
        await engine.dispose()


async def _build_pre_alembic(service: Service, url: str, *, drop_reconciled: bool) -> bool:
    """Build the schema the way the pre-Alembic path did, optionally re-creating its drift.

    `Base.metadata.create_all` is what every existing deployment's database was built by. (The
    additive reconcile that ran beside it is a no-op on a database `create_all` just built, so
    there is nothing to replay here — its *effect* is what the drift arm strips out below.)
    With *drop_reconciled*, the columns the reconcile was responsible for are dropped again,
    leaving the database in the state a deployment is in when it last booted before those
    columns existed — the #214 / #218 state. Returns whether anything was dropped, so the
    caller can skip an arm that would assert nothing.
    """
    engine = create_async_engine(url)
    dropped: list[str] = []
    try:
        async with engine.begin() as conn:
            for metadata in service.metadatas:
                await conn.run_sync(metadata.create_all)
            if drop_reconciled:
                for metadata in service.metadatas:
                    for table in metadata.sorted_tables:
                        for column in _reconcilable_columns(table):
                            await conn.exec_driver_sql(
                                f'ALTER TABLE "{table.name}" DROP COLUMN "{column}"'
                            )
                            dropped.append(f"{table.name}.{column}")
        if dropped:
            print(f"  dropped to simulate drift: {', '.join(dropped)}")
    finally:
        await engine.dispose()
    return bool(dropped)


def _reconcilable_columns(table: sa.Table) -> list[str]:
    """Columns the additive reconcile can restore *exactly*, so dropping one is a fair test.

    A column qualifies when it carries a literal SQL server default — the reconcile re-adds it
    `NOT NULL DEFAULT …`, identical to what `create_table` would have produced. Everything else
    is excluded on purpose: a `NOT NULL` column with no server default comes back **nullable**
    (there is nothing to backfill populated rows with — the documented limit, and #903's cause),
    and a column inside a primary key, unique constraint or index takes that object with it when
    it is dropped, which is beyond any additive repair. Dropping either kind would assert that
    the reconcile does something it has never claimed to do.
    """
    constrained = {
        column.name
        for constraint in table.constraints
        if isinstance(constraint, ColumnCollectionConstraint)
        for column in constraint.columns
    }
    constrained |= {column.name for index in table.indexes for column in index.columns}
    return [
        column.name
        for column in table.columns
        if column.name not in constrained
        and isinstance(column.server_default, DefaultClause)
        and isinstance(getattr(column.server_default.arg, "text", column.server_default.arg), str)
    ]


@asynccontextmanager
async def _database(admin_url: str, name: str) -> AsyncIterator[str]:
    """An empty Postgres database of its own, created on enter and dropped on exit.

    Every service shares one database in production, but a *gate* must not: "fresh install"
    means nothing if a previous arm left its tables behind, and the adoption arms need a
    database holding this service's tables and no version table. So each arm gets a throwaway
    database, created through an AUTOCOMMIT connection to the one the URL names (`CREATE
    DATABASE` cannot run inside a transaction). Yields the URL of the new database.
    """
    admin = sa.engine.make_url(admin_url)

    async def run(*statements: str) -> None:
        engine = create_async_engine(str(admin), isolation_level="AUTOCOMMIT")
        try:
            async with engine.connect() as conn:
                for statement in statements:
                    await conn.exec_driver_sql(statement)
        finally:
            await engine.dispose()

    await run(f'DROP DATABASE IF EXISTS "{name}"', f'CREATE DATABASE "{name}"')
    try:
        yield str(admin.set(database=name))
    finally:
        await run(f'DROP DATABASE IF EXISTS "{name}"')


# ── Entry point ───────────────────────────────────────────────────────────────


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="command", required=True)

    services = sub.add_parser("services", help="list the migration-managed services")
    services.set_defaults(func=cmd_services)

    baseline = sub.add_parser("baseline", help="render a service's initial revision")
    baseline.add_argument("service")
    baseline.set_defaults(func=cmd_baseline)

    new = sub.add_parser("new", help="create the next empty revision, to hand-write")
    new.add_argument("service")
    new.add_argument("message", help="short description, e.g. 'backfill suggestions_enabled'")
    new.set_defaults(func=cmd_new)

    check = sub.add_parser("check", help="upgrade from empty, then fail on model/revision drift")
    check.add_argument("services", nargs="*", help="default: every migration-managed service")
    check.add_argument("--url", default=None, help="database URL (default: a throwaway SQLite)")
    check.set_defaults(func=cmd_check)

    gate = sub.add_parser("gate", help="the CI gate: fresh, idempotent, and adoption paths")
    gate.add_argument("services", nargs="*", help="default: every migration-managed service")
    gate.add_argument("--url", required=True, help="Postgres URL of an existing database")
    gate.set_defaults(func=cmd_gate)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        exit_code: int = args.func(args)
    except MigrateError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
