"""notes baseline — the schema as it stood at Alembic adoption.

Revision 0001, the base of this service's history.

Generated by ``uv run python scripts/migrate.py baseline notes``. Every operation goes
through ``epicurus_core.db.ops`` (``ep.``), which creates a table that is absent and additively
reconciles one that is already there — so this revision applies both to an empty database and
to a deployment provisioned before notes adopted Alembic (ADR-XXXX). Later revisions
are ordinary Alembic; only a baseline needs this.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from epicurus_core.db import ops as ep

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create (or additively reconcile) every table notes owns."""
    # ### commands auto generated by Alembic - please adjust! ###
    ep.create_table(
        "note_folders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "path", name="uq_note_folders_tenant_path"),
    )
    ep.create_index(ep.f("ix_note_folders_tenant"), "note_folders", ["tenant"], unique=False)
    ep.create_table(
        "note_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("slug", sa.String(length=512), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(ep.f("ix_note_versions_tenant"), "note_versions", ["tenant"], unique=False)
    ep.create_index(
        "ix_note_versions_tenant_slug", "note_versions", ["tenant", "slug"], unique=False
    )
    ep.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("slug", sa.String(length=512), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "slug", name="uq_notes_tenant_slug"),
    )
    ep.create_index(ep.f("ix_notes_tenant"), "notes", ["tenant"], unique=False)
    ep.create_table(
        "notes_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("sid", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=512), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("proposed_content", sa.Text(), nullable=False),
        sa.Column("origin", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(ep.f("ix_notes_suggestions_sid"), "notes_suggestions", ["sid"], unique=False)
    ep.create_index(
        ep.f("ix_notes_suggestions_tenant"), "notes_suggestions", ["tenant"], unique=False
    )
    ep.create_table(
        "notes_suggestion_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("sid", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=512), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("origin", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("proposed_content", sa.Text(), nullable=False),
        sa.Column("applied_content", sa.Text(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("proposed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "decided_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(
        ep.f("ix_notes_suggestion_decisions_tenant"),
        "notes_suggestion_decisions",
        ["tenant"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop every table notes owns. Destroys data; never automatic."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notes_suggestion_decisions_tenant"), table_name="notes_suggestion_decisions"
    )
    op.drop_table("notes_suggestion_decisions")
    op.drop_index(op.f("ix_notes_suggestions_tenant"), table_name="notes_suggestions")
    op.drop_index(op.f("ix_notes_suggestions_sid"), table_name="notes_suggestions")
    op.drop_table("notes_suggestions")
    op.drop_index(op.f("ix_notes_tenant"), table_name="notes")
    op.drop_table("notes")
    op.drop_index("ix_note_versions_tenant_slug", table_name="note_versions")
    op.drop_index(op.f("ix_note_versions_tenant"), table_name="note_versions")
    op.drop_table("note_versions")
    op.drop_index(op.f("ix_note_folders_tenant"), table_name="note_folders")
    op.drop_table("note_folders")
    # ### end Alembic commands ###
