"""The migration foundation itself — runner, shared ``env.py``, idempotent baseline ops.

These tests build a **synthetic** service's migration environment in ``tmp_path``: a three-line
``env.py``, a hand-written baseline against :mod:`epicurus_core.db.ops`, and a second revision.
Nothing here imports a service, so what is under test is the foundation the seven service lanes
share rather than any one lane's use of it.

All of it runs on **file-backed** SQLite. The Postgres-only pieces — the advisory lock, and the
real upgrade against the shared database every service lives in — are what the `migrations` CI
gate covers; the lock's *derivation* is pure and tested here.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from pathlib import Path
from typing import Any

import pytest
import sqlalchemy as sa
from alembic.util import AutogenerateDiffsDetected
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine

from epicurus_core.db import ensure_columns
from epicurus_core.db.migrations import (
    advisory_lock_key,
    alembic_config,
    run_migrations,
    version_table_name,
)

SERVICE = "widgets"

_ENV_PY = """
from epicurus_core.db.alembic_env import run

run()
"""

_BASELINE = '''
"""widgets baseline."""

from __future__ import annotations

import sqlalchemy as sa

from epicurus_core.db import ops as ep

revision: str = "0001"
down_revision: str | None = None


def upgrade() -> None:
    ep.create_table(
        "widgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=63), nullable=False),
        sa.Column("label", sa.String(length=32), server_default=sa.text("'none'"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    ep.create_index(ep.f("ix_widgets_tenant"), "widgets", ["tenant"], unique=False)


def downgrade() -> None:
    op.drop_table("widgets")
'''

_SECOND = '''
"""widgets: add note."""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"


def upgrade() -> None:
    op.add_column("widgets", sa.Column("note", sa.String(length=64), nullable=True))


def downgrade() -> None:
    op.drop_column("widgets", "note")
'''


def _models(*, with_note: bool) -> list[sa.MetaData]:
    """The synthetic service's metadata, optionally including the column 0002 adds."""
    metadata = sa.MetaData()
    columns: list[sa.Column[Any]] = [
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("tenant", sa.String(63), nullable=False, index=True),
        sa.Column("label", sa.String(32), server_default="'none'", nullable=False),
    ]
    if with_note:
        columns.append(sa.Column("note", sa.String(64), nullable=True))
    sa.Table("widgets", metadata, *columns)
    return [metadata]


@pytest.fixture
def scripts(tmp_path: Path) -> Path:
    """A migration environment with the baseline only."""
    location = tmp_path / "migrations"
    (location / "versions").mkdir(parents=True)
    (location / "env.py").write_text(_ENV_PY, encoding="utf-8")
    (location / "versions" / "0001_baseline.py").write_text(_BASELINE, encoding="utf-8")
    return location


@pytest.fixture
async def engine(tmp_path: Path) -> AsyncIterator[AsyncEngine]:
    engine = create_async_engine(f"sqlite+aiosqlite:///{tmp_path / 'widgets.sqlite'}")
    try:
        yield engine
    finally:
        await engine.dispose()


async def _migrate(engine: AsyncEngine, scripts: Path, *, with_note: bool = False) -> str:
    return await run_migrations(
        engine,
        service=SERVICE,
        script_location=scripts,
        metadatas=_models(with_note=with_note),
    )


async def _columns(engine: AsyncEngine, table: str = "widgets") -> dict[str, str]:
    def read(sync_conn: sa.Connection) -> dict[str, str]:
        return {c["name"]: str(c["type"]) for c in sa.inspect(sync_conn).get_columns(table)}

    async with engine.connect() as conn:
        return await conn.run_sync(read)


async def _head_recorded(engine: AsyncEngine) -> str | None:
    def read(sync_conn: sa.Connection) -> str | None:
        table = version_table_name(SERVICE)
        if not sa.inspect(sync_conn).has_table(table):
            return None
        return str(sync_conn.exec_driver_sql(f"SELECT version_num FROM {table}").scalar())

    async with engine.connect() as conn:
        return await conn.run_sync(read)


# ── Naming and the lock key ───────────────────────────────────────────────────


def test_each_service_gets_its_own_version_table() -> None:
    """Seven services share one database; a shared ``alembic_version`` would break all seven."""
    assert version_table_name("storage") == "alembic_version_storage"
    assert version_table_name("core-app") == "alembic_version_core_app", "hyphen needs quoting"
    assert len({version_table_name(s) for s in ("storage", "calendar", "tasks")}) == 3


def test_the_lock_key_is_deterministic_across_processes() -> None:
    """It must be stable: two replicas derive it independently and have to collide on purpose.

    A salted built-in ``hash()`` would give each process a different key, so neither replica
    would ever wait for the other — the exact failure the lock exists to prevent, and invisible
    in a single-process test. Pinning the value is how a refactor that reintroduces ``hash()``
    gets caught.
    """
    assert advisory_lock_key("storage") == advisory_lock_key("storage")
    assert advisory_lock_key("storage") == -7526409015360701717
    assert advisory_lock_key("storage") != advisory_lock_key("calendar")
    assert -(2**63) <= advisory_lock_key("core-app") < 2**63, "must fit a Postgres bigint"


# ── The three starting states ─────────────────────────────────────────────────


async def test_an_empty_database_is_classified_fresh_and_reaches_head(
    engine: AsyncEngine, scripts: Path
) -> None:
    assert await _migrate(engine, scripts) == "fresh"
    assert await _head_recorded(engine) == "0001"
    assert set(await _columns(engine)) == {"id", "tenant", "label"}


async def test_a_second_run_is_classified_managed(engine: AsyncEngine, scripts: Path) -> None:
    await _migrate(engine, scripts)
    assert await _migrate(engine, scripts) == "managed"


async def test_a_database_with_tables_but_no_version_table_is_adopted(
    engine: AsyncEngine, scripts: Path
) -> None:
    """The pre-Alembic deployment: tables built by ``create_all``, nothing recording a head."""
    async with engine.begin() as conn:
        for metadata in _models(with_note=False):
            await conn.run_sync(metadata.create_all)
    assert await _head_recorded(engine) is None

    assert await _migrate(engine, scripts) == "adopted"
    assert await _head_recorded(engine) == "0001"


async def test_another_services_tables_do_not_make_this_one_look_adopted(
    engine: AsyncEngine, scripts: Path
) -> None:
    """Classification keys on *this* service's tables, not on the database being non-empty.

    Every service shares one database, so by the time the fourth service starts for the first
    time the database is full of tables — none of them its own. Mistaking that for a pre-Alembic
    deployment would be harmless today and confusing forever in the logs.
    """
    async with engine.begin() as conn:
        await conn.exec_driver_sql("CREATE TABLE someone_elses_table (id INTEGER PRIMARY KEY)")
        await conn.exec_driver_sql("CREATE TABLE alembic_version_other (version_num VARCHAR(32))")
    assert await _migrate(engine, scripts) == "fresh"


# ── Revisions after the baseline ──────────────────────────────────────────────


async def test_a_later_revision_applies_to_an_adopted_database(
    engine: AsyncEngine, scripts: Path
) -> None:
    """The case a ``stamp``-based adoption would have silently skipped.

    A deployment that last booted before this service adopted Alembic, upgrading to a release
    that already carries a second revision: the baseline reconciles what is there, then 0002
    applies on top. Had adoption worked by stamping the head revision instead, 0002 — which in
    the real #903 case is a **backfill** — would never have run, which is why the baseline is
    idempotent rather than stamped (ADR-XXXX).
    """
    (scripts / "versions" / "0002_add_note.py").write_text(_SECOND, encoding="utf-8")
    async with engine.begin() as conn:
        for metadata in _models(with_note=False):
            await conn.run_sync(metadata.create_all)

    assert await _migrate(engine, scripts, with_note=True) == "adopted"
    assert await _head_recorded(engine) == "0002"
    assert "note" in await _columns(engine)


async def test_drift_between_models_and_revisions_is_detected(
    engine: AsyncEngine, scripts: Path
) -> None:
    """``alembic check`` through the shared env.py — the gate the CI job runs per service.

    The models gain a column and nobody writes a revision: that is #214 and #218, and it has to
    fail loudly at review time rather than as a ``column … does not exist`` in production.
    """
    await _migrate(engine, scripts)

    def check(sync_conn: sa.Connection) -> None:
        from alembic import command

        command.check(
            alembic_config(
                script_location=scripts,
                metadatas=_models(with_note=True),
                version_table=version_table_name(SERVICE),
                connection=sync_conn,
            )
        )

    async with engine.connect() as conn:
        with pytest.raises(AutogenerateDiffsDetected, match="note"):
            await conn.run_sync(check)


async def test_check_ignores_tables_this_service_does_not_own(
    engine: AsyncEngine, scripts: Path
) -> None:
    """Without the ``include_name`` filter no service could ever pass its own drift check.

    One database, seven services, disjoint tables: an unfiltered compare sees six services'
    tables as "present but not in my models" and proposes dropping them, so ``alembic check``
    would fail forever and the gate would be worthless.
    """
    await _migrate(engine, scripts)
    async with engine.begin() as conn:
        await conn.exec_driver_sql("CREATE TABLE calendar_events (id INTEGER PRIMARY KEY)")

    def check(sync_conn: sa.Connection) -> None:
        from alembic import command

        command.check(
            alembic_config(
                script_location=scripts,
                metadatas=_models(with_note=False),
                version_table=version_table_name(SERVICE),
                connection=sync_conn,
            )
        )

    async with engine.connect() as conn:
        await conn.run_sync(check)  # no AutogenerateDiffsDetected


# ── The idempotent baseline operations ────────────────────────────────────────


async def test_the_baseline_repairs_a_table_missing_a_defaulted_column(
    engine: AsyncEngine, scripts: Path
) -> None:
    """A column with a literal server default comes back exactly as ``create_table`` made it.

    This is the #214 / #218 state: the table exists from an older release, the model has since
    gained a column, and the deployment has never had it. The reconcile arm adds it ``NOT NULL``
    with the default, which backfills the rows already there.
    """
    async with engine.begin() as conn:
        await conn.exec_driver_sql(
            "CREATE TABLE widgets (id INTEGER PRIMARY KEY, tenant VARCHAR(63))"
        )
        await conn.exec_driver_sql("INSERT INTO widgets (tenant) VALUES ('t1')")

    assert await _migrate(engine, scripts) == "adopted"
    assert "label" in await _columns(engine)
    async with engine.connect() as conn:
        value = (await conn.execute(sa.text("SELECT label FROM widgets"))).scalar()
    assert value == "none", "existing rows must be backfilled by the server default"


async def test_the_baseline_adds_a_missing_index_but_not_a_duplicate(
    engine: AsyncEngine, scripts: Path
) -> None:
    """``create_index`` is idempotent in both directions: adds when absent, skips when present."""

    def index_names(sync_conn: sa.Connection) -> list[str]:
        return [ix["name"] or "" for ix in sa.inspect(sync_conn).get_indexes("widgets")]

    await _migrate(engine, scripts)
    async with engine.connect() as conn:
        assert await conn.run_sync(index_names) == ["ix_widgets_tenant"]

    # Forget the version table and run the baseline again over the finished schema: every
    # operation in it has to be a no-op, index included.
    async with engine.begin() as conn:
        await conn.exec_driver_sql(f"DROP TABLE {version_table_name(SERVICE)}")
    assert await _migrate(engine, scripts) == "adopted"
    async with engine.connect() as conn:
        assert await conn.run_sync(index_names) == ["ix_widgets_tenant"]


async def test_the_reconcile_arm_reuses_the_audited_helper(engine: AsyncEngine) -> None:
    """``ops.create_table``'s repair arm is ``ensure_columns``, not a second implementation.

    The rules for adding a column to a populated table — reproduce a literal server default and
    its ``NOT NULL``, relax ``NOT NULL`` when there is nothing to backfill with — were audited
    once (#249, ADR-0067). This pins that the reconcile arm still behaves that way rather than
    having grown its own copy.
    """
    metadata = sa.MetaData()
    table = sa.Table(
        "audited",
        metadata,
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("with_default", sa.String(8), server_default="'x'", nullable=False),
        sa.Column("without_default", sa.String(8), nullable=False),
    )
    async with engine.begin() as conn:
        await conn.exec_driver_sql("CREATE TABLE audited (id INTEGER PRIMARY KEY)")
        await conn.exec_driver_sql("INSERT INTO audited (id) VALUES (1)")
        await conn.run_sync(
            lambda sync: ensure_columns(sync, table, [c.name for c in table.columns])
        )

    columns = await _columns(engine, "audited")
    assert set(columns) == {"id", "with_default", "without_default"}

    def describe(sync_conn: sa.Connection) -> dict[str, bool]:
        return {
            c["name"]: bool(c["nullable"]) for c in sa.inspect(sync_conn).get_columns("audited")
        }

    async with engine.connect() as conn:
        nullability = await conn.run_sync(describe)
    assert nullability["with_default"] is False, "a server default can satisfy NOT NULL"
    assert nullability["without_default"] is True, "nothing to backfill: added nullable (#903)"


# ── The shared env.py refuses to run half-configured ──────────────────────────


async def test_the_runner_is_the_only_supported_entry_point(
    engine: AsyncEngine, scripts: Path
) -> None:
    """Driving Alembic without the attributes ``env.py`` needs fails with a pointed message.

    There is no ``alembic.ini`` and no offline (``--sql``) mode: both would need a connection
    and a metadata list they cannot get from a static file, and an offline render could not
    consult the live table shape the idempotent baseline depends on.
    """
    from alembic import command

    config = alembic_config(
        script_location=scripts,
        metadatas=_models(with_note=False),
        version_table=version_table_name(SERVICE),
    )
    with pytest.raises(RuntimeError, match="online only"):
        command.upgrade(config, "head")
