"""mail baseline — the schema as it stood at Alembic adoption.

Revision 0001, the base of this service's history.

Generated by ``uv run python scripts/migrate.py baseline mail``. Every operation goes
through ``epicurus_core.db.ops`` (``ep.``), which creates a table that is absent and additively
reconciles one that is already there — so this revision applies both to an empty database and
to a deployment provisioned before mail adopted Alembic (ADR-XXXX). Later revisions
are ordinary Alembic; only a baseline needs this.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from epicurus_core.db import ops as ep

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create (or additively reconcile) every table mail owns."""
    # ### commands auto generated by Alembic - please adjust! ###
    ep.create_table(
        "mail_category",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("category_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("unread", sa.Integer(), nullable=True),
        sa.Column("preview_sender", sa.String(length=512), nullable=False),
        sa.Column("preview_subject", sa.String(length=1024), nullable=False),
        sa.Column("has_preview", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant_id", "label", "category_id", name="uq_mail_category"),
    )
    ep.create_index(ep.f("ix_mail_category_label"), "mail_category", ["label"], unique=False)
    ep.create_index(
        ep.f("ix_mail_category_tenant_id"), "mail_category", ["tenant_id"], unique=False
    )
    ep.create_table(
        "mail_label",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("label_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("unread", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant_id", "label_id", name="uq_mail_label"),
    )
    ep.create_index(ep.f("ix_mail_label_tenant_id"), "mail_label", ["tenant_id"], unique=False)
    ep.create_table(
        "mail_landing",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("next_cursor", sa.Text(), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant_id", "label", name="uq_mail_landing"),
    )
    ep.create_index(ep.f("ix_mail_landing_tenant_id"), "mail_landing", ["tenant_id"], unique=False)
    ep.create_table(
        "mail_sync",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("history_id", sa.BigInteger(), nullable=True),
        sa.Column("uid_validity", sa.BigInteger(), nullable=True),
        sa.Column("uid_next", sa.BigInteger(), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant_id", name="uq_mail_sync"),
    )
    ep.create_index(ep.f("ix_mail_sync_tenant_id"), "mail_sync", ["tenant_id"], unique=False)
    ep.create_table(
        "mail_thread",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=63), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("thread_id", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=1024), nullable=False),
        sa.Column("sender", sa.String(length=512), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("date", sa.String(length=128), nullable=False),
        sa.Column("sort_ts", sa.BigInteger(), nullable=False),
        sa.Column("unread", sa.Boolean(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column(
            "cached_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("tenant_id", "label", "thread_id", name="uq_mail_thread"),
    )
    ep.create_index(ep.f("ix_mail_thread_label"), "mail_thread", ["label"], unique=False)
    ep.create_index(ep.f("ix_mail_thread_tenant_id"), "mail_thread", ["tenant_id"], unique=False)
    ep.create_index(ep.f("ix_mail_thread_thread_id"), "mail_thread", ["thread_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop every table mail owns. Destroys data; never automatic."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mail_thread_thread_id"), table_name="mail_thread")
    op.drop_index(op.f("ix_mail_thread_tenant_id"), table_name="mail_thread")
    op.drop_index(op.f("ix_mail_thread_label"), table_name="mail_thread")
    op.drop_table("mail_thread")
    op.drop_index(op.f("ix_mail_sync_tenant_id"), table_name="mail_sync")
    op.drop_table("mail_sync")
    op.drop_index(op.f("ix_mail_landing_tenant_id"), table_name="mail_landing")
    op.drop_table("mail_landing")
    op.drop_index(op.f("ix_mail_label_tenant_id"), table_name="mail_label")
    op.drop_table("mail_label")
    op.drop_index(op.f("ix_mail_category_tenant_id"), table_name="mail_category")
    op.drop_index(op.f("ix_mail_category_label"), table_name="mail_category")
    op.drop_table("mail_category")
    # ### end Alembic commands ###
